### ISSUE TITLE
Fix issues in v0.1.2

### ISSUE THREAD

**Issue by Sunbelife** [Llama-Group/Project-Llama#101] opened 2016-08-11 08:29 UTC
I found three error:
1、When i build a specific example , some code style file not found:
log in : https://docs.google.com/document/d/1uNgqy37CCDTFVXQ1YGGaOhqfinkjI-7X6pGjvkDtMU8/edit
2、'benchmark/benchmark.h' file not found
3、When i run the install_benchmark.sh , here came to a error:
`make: * No targets specified and no makefile found. Stop.`
4、When the project's folder's name isn't 'Project-llama', terminal will return an error : 
Project name must be Project-Llama!

Full test report in : https://docs.google.com/spreadsheets/d/12CtQt8DIhwDeDhFpL6AeZT8wPNDeH5hcjZvlCyYzpOA/edit#gid=0

**Comment by 0xsuu** [comment] 2016-08-11 09:04
1，2，3 caused by not cloning sub-modules, which should be covered in the install script.
4 will be fixed after refurbish build.sh

**Comment by 0xsuu** [comment] 2016-08-13 10:46
Fixed 1,2,3, 4 remains until #99 done.

**Closed as completed by 0xsuu** 2016-08-13 10:46 UTC
